### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [s-samusik/Page-Telegram#1]
Quite good, in general, but need one correction. 
Need 2 separate scrolls instead of one general scroll
![image](https://user-images.githubusercontent.com/5592397/90666952-cba6ea00-e256-11ea-95a4-1765ac522ab6.png)

**Comment by IlyaMokin** [comment]
But why you removed messages from right area? It looks like on small screen it's not possible to enter message
![image](https://user-images.githubusercontent.com/5592397/92306180-b986b480-ef95-11ea-8aca-bdce0bb6ccd7.png)

**Comment by s-samusik** [comment]
I've fixed message area.
